## Test

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("TestDataFRC2018.csv", header=2, sep=" *,", engine="python")

In [3]:
# Remove blank rows
print(f"Number of rows before cleaning: {data.shape[0]}")
data.dropna(axis=0,inplace=True)
f"Number of rows after cleaning: {data.shape[0]}"

Number of rows before cleaning: 70

'Number of rows after cleaning: 68'

In [4]:
data['Match Number'] = data['Match Number'].astype(int)
data['Team Number'] = data['Team Number'].astype(int)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 68 entries, 0 to 69
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Date Time             68 non-null     object
 1   Time Stamp            68 non-null     int64
 2   Match Number          68 non-null     int32
 3   Team Number           68 non-null     int32
 4   Alliance Colour       68 non-null     object
 5   Line                  68 non-null     int64
 6   Switch                68 non-null     int64
 7   Scale                 68 non-null     int64
 8   Exchange              68 non-null     int64
 9   Home Switch           68 non-null     int64
 10  Opponent Switch       68 non-null     int64
 11  Scale.1               68 non-null     int64
 12  Exchange.1            68 non-null     int64
 13  Climb Attempted       68 non-null     int64
 14  Climb Succeeded       68 non-null     int64
 15  Park                  68 non-null     int64
 16  Support Other Robots  68 non-null     int64
 17  Fouls                 68 non-null     int64
 18  Tech fouls            68 non-null     int64
 19  Navigation            68 non-null     int64
 20  OA Quality            68 non-null     int64
dtypes: int32(2), int64(17), object(2)
memory usage: 11.2+ KB

In [5]:
renameDict = {
    "Switch" : "Auto Switch",
    "Scale" : "Auto Scale",
    "Exchange" : "Auto Exchange",
    "Scale.1" : "Teleop Scale",
    "Exchange.1" : "Teleop Exchange",
}
data.rename(columns=renameDict, inplace=True)

In [6]:
columnsToDrop = [
    "Date Time",
    "Time Stamp",
    "Alliance Colour",
    "Match Number"
]
data.drop(columns=columnsToDrop, inplace=True)

In [7]:
data.groupby('Team Number').mean()

,Line,Auto Switch,Auto Scale,Auto Exchange,Home Switch,Opponent Switch,Teleop Scale,Teleop Exchange,Climb Attempted,Climb Succeeded,Park,Support Other Robots,Fouls,Tech fouls,Navigation,OA Quality
Team Number,,,,,,,,,,,,,,,,
865,0.500000,0.000000,0.50,0.0,0.000000,0.0,1.500000,0.500000,0.500000,0.000000,0.00,0.0,0.0,0.000000,1.000000,1.500000
1075,1.000000,0.000000,0.00,0.0,0.000000,0.5,0.500000,0.000000,0.000000,0.000000,0.50,0.0,0.0,0.000000,1.500000,1.500000
1114,1.000000,0.000000,0.00,0.0,1.000000,0.0,8.000000,0.000000,1.000000,1.000000,0.00,1.0,0.0,0.000000,3.000000,2.000000
1241,1.000000,0.000000,1.00,0.0,0.500000,1.5,3.500000,0.000000,1.000000,1.000000,0.00,0.0,0.0,0.000000,1.500000,2.000000
1285,0.000000,0.000000,0.00,0.0,0.000000,0.0,0.800000,0.800000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.400000,1.200000
1325,1.000000,0.000000,0.00,0.0,4.000000,0.0,1.000000,0.000000,1.000000,1.000000,0.00,0.0,0.0,0.000000,3.000000,3.000000
1350,1.000000,0.000000,0.00,0.0,0.000000,0.0,6.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.000000,1.000000
1360,1.000000,2.000000,0.00,0.0,2.000000,1.0,3.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.000000,2.000000
2013,0.500000,0.000000,0.50,0.0,1.500000,2.0,2.000000,1.000000,0.500000,0.000000,0.50,0.0,0.0,0.000000,3.000000,2.500000
2056,1.000000,0.000000,0.00,0.0,0.000000,1.0,5.000000,0.000000,1.000000,0.000000,1.00,0.0,0.0,0.000000,3.000000,3.000000
2604,1.000000,0.000000,0.00,0.0,0.500000,2.5,0.000000,3.000000,0.000000,0.000000,0.50,0.0,0.0,0.000000,1.500000,1.500000
2609,1.000000,2.000000,0.00,0.0,3.000000,0.0,0.000000,4.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,2.000000,1.000000
2702,0.333333,0.000000,0.00,0.0,0.000000,0.0,0.666667,0.000000,0.333333,0.000000,0.00,0.0,0.0,0.000000,1.666667,1.666667
2852,1.000000,0.000000,0.00,0.0,1.500000,0.0,1.750000,0.000000,0.500000,0.500000,0.25,0.0,0.0,0.000000,1.250000,1.250000
3161,1.000000,0.666667,0.00,0.0,0.666667,0.0,1.000000,2.666667,0.666667,0.666667,0.00,0.0,0.0,0.000000,2.000000,2.333333
3683,1.000000,1.000000,0.00,0.0,0.000000,6.0,0.000000,0.000000,1.000000,0.000000,1.00,0.0,0.0,0.000000,3.000000,3.000000
3739,0.500000,0.000000,0.00,0.0,2.000000,0.5,0.000000,0.000000,0.500000,0.000000,0.00,0.0,0.0,0.000000,1.500000,1.000000
4069,1.000000,0.000000,0.50,0.0,1.000000,0.0,1.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.500000,1.000000
4308,1.000000,1.000000,0.00,0.0,0.000000,1.0,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,2.500000,1.000000
4343,1.000000,0.000000,0.00,0.0,3.000000,0.0,0.000000,3.333333,1.000000,0.333333,0.00,0.0,0.0,0.000000,1.666667,2.000000
4618,1.000000,0.000000,0.00,0.0,0.000000,0.0,0.000000,5.000000,1.000000,0.000000,1.00,0.0,0.0,0.000000,1.000000,2.000000
4678,1.000000,0.000000,1.25,0.0,1.000000,1.5,1.500000,1.250000,1.000000,0.250000,0.75,0.0,0.0,0.000000,2.250000,2.250000
4917,1.000000,0.000000,1.00,0.0,0.000000,8.0,3.000000,0.000000,1.000000,1.000000,0.00,0.0,0.0,0.000000,1.000000,1.000000
5039,1.000000,0.000000,0.00,0.0,2.000000,0.0,0.000000,2.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.000000,2.000000
5719,1.000000,0.000000,0.00,0.0,1.000000,0.0,2.333333,2.333333,0.000000,0.000000,0.00,0.0,0.0,0.000000,2.000000,1.333333
6336,1.000000,1.000000,0.00,0.0,5.000000,0.0,0.000000,1.000000,1.000000,0.000000,0.00,0.0,0.0,0.000000,1.000000,1.000000
6342,0.666667,0.000000,0.00,0.0,1.000000,0.0,0.000000,3.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.666667,2.000000
6378,0.500000,0.500000,0.00,0.0,2.500000,0.5,0.000000,3.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,2.000000,2.000000
6878,0.500000,0.000000,0.00,0.0,0.500000,0.0,0.000000,2.000000,0.500000,0.500000,0.00,0.0,0.0,0.000000,1.500000,1.500000
7475,0.666667,0.000000,0.00,0.0,1.333333,0.0,0.000000,1.333333,0.000000,0.000000,0.00,0.0,0.0,0.333333,1.000000,1.000000
7509,1.000000,0.666667,0.00,0.0,1.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.000000,1.000000
7623,1.000000,2.000000,0.00,0.0,0.000000,0.0,0.000000,1.000000,0.000000,0.000000,0.00,0.0,0.0,0.000000,1.500000,1.000000